#! /bin/sh
### BEGIN INIT INFO
# Provides:          thermPollerInit
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: thermPoller startup script
### END INIT INFO

#PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions
# If you need to source some other scripts, do it here

case "$1" in
  start)
    log_begin_msg "Starting thermPollerMaster.sh"
    sudo -u username "/usr/local/bin/XBeeThermClient/thermPollerMaster.sh" &
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping thermPollerMaster.sh"

    killall thermPollerMaster.sh
    killall thermPoller

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/thermPollerInit {start|stop}"
    exit 1
    ;;
esac